apiVersion: v1
kind: Service
metadata:
  name: app-evaluation-service
  namespace: evaluation-service
spec:
  selector:
    app: app-evaluation-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  type: ClusterIP
