apiVersion: batch/v1
kind: Job
metadata:
  name: auth-db-init
  namespace: auth-service
  annotations:
    # 1. Diz ao ArgoCD para rodar isso ANTES do Deployment
    argocd.argoproj.io/hook: PreSync
    # 2. Diz ao ArgoCD para apagar o Job antigo depois que der sucesso, para não travar o próximo deploy
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres:15-alpine 
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for database..."
              until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER"; do
                sleep 2
              done
              
              echo "Running init.sql..."
              PGPASSWORD="$POSTGRES_PASSWORD" psql \
                -h "$POSTGRES_HOST" \
                -p "$POSTGRES_PORT" \
                -U "$POSTGRES_USER" \
                -d "$POSTGRES_DB" \
                -f /sql/init.sql
              echo "Table created successfully"
          volumeMounts:
            - name: sql-volume
              mountPath: /sql
          envFrom:
            - secretRef:
                name: auth-db-secret 
            - secretRef:
                name: auth-db-secret-host
      volumes:
        - name: sql-volume
          configMap:
            name: db-auth-service-init-sql