apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gabriel-cupertino/tech-challenge-gitops.git
    targetRevision: main
    path: flag-service
  destination:
    server: https://kubernetes.default.svc
    namespace: flag-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
